# Generated by Django 5.0.14 on 2026-07-09 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='desired_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RestaurantStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_percent', models.FloatField(blank=True, null=True)),
                ('ram_percent', models.FloatField(blank=True, null=True)),
                ('disk_percent', models.FloatField(blank=True, null=True)),
                ('app_version', models.CharField(blank=True, default='', max_length=50)),
                ('unsynced_count', models.IntegerField(blank=True, null=True)),
                ('last_order_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='tenants.restaurant')),
            ],
        ),
    ]
