# Generated by Django 5.0.14 on 2026-07-09 19:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_restaurant_desired_version_restaurant_is_online_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_type', models.CharField(choices=[('block_system', 'Tizimni bloklash'), ('unblock_system', 'Blokdan chiqarish'), ('force_license_renew', 'Litsenziyani majburiy yangilash'), ('force_sync', 'Majburiy sinxronizatsiya'), ('update_app', "Yangilanishni o'rnatish"), ('restart_services', 'Servislarni qayta ishga tushirish')], max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('sent', 'Yuborildi'), ('acknowledged', 'Qabul qilindi'), ('completed', 'Bajarildi'), ('failed', 'Xato')], db_index=True, default='pending', max_length=15)),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='tenants.restaurant')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['restaurant', 'status'], name='tenants_rem_restaur_08212a_idx')],
            },
        ),
    ]
