# Generated by Django 5.0.14 on 2026-07-09 20:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_remotecommand'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantAdminAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami +998xxxxxxxxx, 998xxxxxxxxx yoki xxxxxxxxx formatida bo'lishi kerak.", regex='^\\+?(998)?\\d{9}$')])),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('password_hash', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_account', to='tenants.restaurant')),
            ],
        ),
    ]
