# Generated by Django 5.2 on 2026-07-10 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_restaurantadminaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], db_index=True, max_length=10)),
                ('logger_name', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField()),
                ('traceback', models.TextField(blank=True, default='')),
                ('module', models.CharField(blank=True, default='', max_length=200)),
                ('func_name', models.CharField(blank=True, default='', max_length=200)),
                ('line_no', models.PositiveIntegerField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(db_index=True)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_error_logs', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_logs', to='tenants.restaurant')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['restaurant', 'is_resolved'], name='tenants_err_restaur_bd21cb_idx'), models.Index(fields=['level', 'is_resolved'], name='tenants_err_level_cdb57f_idx')],
            },
        ),
    ]
