# Generated by Django 5.2 on 2026-07-11 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_errorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncedOrder',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order_type', models.CharField(default='dine_in', max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('waiter_name', models.CharField(blank=True, max_length=100)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synced_orders', to='tenants.restaurant')),
            ],
            options={
                'ordering': ['-closed_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncedOrderItem',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tenants.syncedorder')),
            ],
        ),
        migrations.CreateModel(
            name='SyncedPayment',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(max_length=20)),
                ('is_voided', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.syncedorder')),
            ],
        ),
    ]
