# Generated by Django 5.2 on 2026-07-23 19:10

import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_demorequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='subdomain',
            field=models.SlugField(blank=True, help_text="Restoran uchun unikal subdomen (masalan: 'sim-sim')", null=True, unique=True, validators=[tenants.models.validate_subdomain]),
        ),
    ]
