# Generated by Django 5.2 on 2026-08-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_restaurant_subdomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='masalan: manager, kassir, ofitsiant', max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text="Qisqa tavsif, masalan: 'Kassa va to'lovlar'", max_length=200)),
                ('version', models.CharField(max_length=30)),
                ('platform', models.CharField(choices=[('android', 'Android')], default='android', max_length=20)),
                ('size_mb', models.DecimalField(decimal_places=1, max_digits=6)),
                ('min_os', models.CharField(default='Android 8.0', max_length=50)),
                ('is_required', models.BooleanField(default=False, help_text='Majburiy yangilanish sifatida belgilansinmi')),
                ('apk_file', models.FileField(help_text="Admin shu yerdan APK faylini yuklaydi - havola emas, fayl o'zi bizning serverda saqlanadi.", upload_to='mobile_apps/')),
                ('notes', models.JSONField(blank=True, default=list, help_text="O'zgarishlar ro'yxati (matn qatorlari)")),
                ('is_active', models.BooleanField(default=True, help_text="O'chirilsa ro'yxatda ko'rinmaydi")),
                ('released_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
