# Generated by Django 5.2 on 2026-08-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_mobileapp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobileapp',
            options={'ordering': ['name', 'platform']},
        ),
        migrations.AlterField(
            model_name='mobileapp',
            name='apk_file',
            field=models.FileField(help_text="Admin shu yerdan o'rnatuvchi faylni (APK yoki Windows uchun EXE/MSI) yuklaydi - havola emas, fayl o'zi bizning serverda saqlanadi.", upload_to='mobile_apps/'),
        ),
        migrations.AlterField(
            model_name='mobileapp',
            name='min_os',
            field=models.CharField(blank=True, default='', help_text="masalan 'Android 8.0' yoki 'Windows 10 64-bit'", max_length=50),
        ),
        migrations.AlterField(
            model_name='mobileapp',
            name='platform',
            field=models.CharField(choices=[('android', 'Android'), ('windows', 'Windows')], default='android', max_length=20),
        ),
        migrations.AlterField(
            model_name='mobileapp',
            name='slug',
            field=models.SlugField(help_text='masalan: manager, kassir, ofitsiant', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='mobileapp',
            constraint=models.UniqueConstraint(fields=('slug', 'platform'), name='unique_mobileapp_slug_platform'),
        ),
    ]
