# Generated by Django 5.2 on 2026-08-01 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_alter_mobileapp_options_alter_mobileapp_apk_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_label', models.CharField(help_text="masalan: 'Tarif A'", max_length=50)),
                ('title', models.CharField(help_text="masalan: 'Boshlang'ich'", max_length=100)),
                ('subtitle', models.CharField(blank=True, default='', help_text="masalan: 'Bitta zal, bitta kassa'", max_length=200)),
                ('price_label', models.CharField(default='KELISHUV', help_text="masalan: 'KELISHUV' yoki '500 000 so'm/oy'", max_length=50)),
                ('cta_label', models.CharField(default="Bog'lanish", help_text="Tugma matni, masalan: 'Bog'lanish' yoki 'Narxni kelishish'", max_length=50)),
                ('is_highlighted', models.BooleanField(default=False, help_text="Markazda ajratib ko'rsatiladi ('Ko'p tanlanadi' belgisi bilan)")),
                ('is_active', models.BooleanField(default=True, help_text="O'chirilsa sahifada ko'rinmaydi")),
                ('order', models.PositiveIntegerField(default=0, help_text="Chapdan o'ngga tartib - kichik son oldinroq turadi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PricingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('is_included', models.BooleanField(default=True, help_text="Yo'q bo'lsa xira (o'chirilgan) ko'rinishda chiziladi")),
                ('order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='tenants.pricingplan')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
