# Generated by Django 5.2 on 2026-08-01 12:54

from django.db import migrations

PLANS = [
    dict(
        order=1, tier_label='Tarif A', title="Boshlang'ich", subtitle='Bitta zal, bitta kassa',
        price_label='KELISHUV', cta_label="Bog'lanish", is_highlighted=False,
        features=[
            ('1 kassa terminali', True),
            ('QR menyu va hisob', True),
            ('Asosiy savdo hisoboti', True),
            ('Oshxona displeyi', False),
            ("Ko'p filial", False),
        ],
    ),
    dict(
        order=2, tier_label="Tarif B · Ko'p tanlanadi", title='Restoran', subtitle="To'liq zal + oshxona",
        price_label='KELISHUV', cta_label='Narxni kelishish', is_highlighted=True,
        features=[
            ('3 kassa terminali', True),
            ('QR menyu va hisob', True),
            ('Oshxona displeyi', True),
            ('Lokal server (offline)', True),
            ("Ko'p filial", False),
        ],
    ),
    dict(
        order=3, tier_label='Tarif C', title='Tarmoq', subtitle='Bir nechta filial',
        price_label='KELISHUV', cta_label="Bog'lanish", is_highlighted=False,
        features=[
            ('Cheksiz terminal', True),
            ("Ko'p filial boshqaruvi", True),
            ('Konsolidatsiyalangan hisobot', True),
            ('API va maxsus integratsiya', True),
            ("Ajratilgan qo'llab-quvvatlash", True),
        ],
    ),
]


def seed_pricing_plans(apps, schema_editor):
    """
    Veb-saytning "Narx" bo'limi bo'sh holatda demo/mock ko'rsatmasligi uchun
    boshlang'ich 3 ta tarifni bazaga yozadi - keyinchalik admin panelidan
    xohlagancha tahrirlash/qo'shish/o'chirish mumkin. Faqat jadval hali
    bo'sh bo'lsa ishlaydi - bu migratsiya qayta ishga tushsa ham (masalan
    testlarda) admin tomonidan qilingan o'zgarishlarni ustidan yozib
    yubormaydi.
    """
    PricingPlan = apps.get_model('tenants', 'PricingPlan')
    PricingFeature = apps.get_model('tenants', 'PricingFeature')

    if PricingPlan.objects.exists():
        return

    for plan_data in PLANS:
        features = plan_data.pop('features')
        plan = PricingPlan.objects.create(**plan_data)
        for i, (text, is_included) in enumerate(features):
            PricingFeature.objects.create(plan=plan, text=text, is_included=is_included, order=i)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_pricingplan_pricingfeature'),
    ]

    operations = [
        migrations.RunPython(seed_pricing_plans, noop_reverse),
    ]
