"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv
from celery.schedules import crontab

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-cloud-pos-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', '0') == '1'

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '*').split(',') if h.strip()]
if '*' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.extend(['.hamrohpos.uz', '.ismatov.uz', '.example.uz', 'localhost', '127.0.0.1'])

CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if origin.strip()
]
if not CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS = ['https://*.hamrohpos.uz', 'https://*.ismatov.uz', 'https://*.example.uz', 'http://localhost', 'http://127.0.0.1']
CORS_ALLOW_ALL_ORIGINS = True

if os.environ.get('SECURE_PROXY_SSL_HEADER', '0') == '1':
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'drf_spectacular',
    
    # Local apps
    'tenants',
    'sync',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # gunicorn'ning o'zi static fayllarni xizmat qilmaydi va bu yerda
    # nginx yo'q (docs/3'dagi reja hali amalga oshirilmagan) - whitenoise
    # ularni to'g'ridan-to'g'ri WSGI qatlamida siqib/keshlab beradi.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'pos_cloud_db'),
        'USER': os.environ.get('DB_USER', 'cloud_user'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'cloud_password'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '25432'),
        'CONN_MAX_AGE': 600,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'staticfiles': {
        # Manifest (hashed-filename) storage needs `collectstatic` to have
        # already run, or any {% static %} lookup raises - fine for prod
        # (entrypoint.sh runs it before gunicorn starts), but dev/test
        # (runserver, manage.py test) never run it, so they fall back to
        # plain storage where nothing needs to be pre-collected.
        'BACKEND': (
            'whitenoise.storage.CompressedManifestStaticFilesStorage' if not DEBUG
            else 'django.contrib.staticfiles.storage.StaticFilesStorage'
        ),
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '10/minute',
        'user': '100/minute',
    }
}

# Test rejimida throttling o'chiriladi - suite bitta manzildan yuzlab so'rov
# yuboradi, throttle hisoblagichlari esa Redis'da test yugurishlari orasida
# ham saqlanib qolib, tasodifiy 429'lar bilan testlarni sindiradi.
# Rate'lar ham None: ActivationView throttle_classes'ni klass darajasida
# o'zi e'lon qiladi va DEFAULT_THROTTLE_CLASSES bo'shligi unga ta'sir
# qilmaydi - rate None esa har qanday SimpleRateThrottle'ni o'chiradi.
if 'test' in sys.argv:
    REST_FRAMEWORK['DEFAULT_THROTTLE_CLASSES'] = []
    REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {'anon': None, 'user': None}

SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# Celery settings
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://localhost:26379/0')
CELERY_RESULT_BACKEND = os.environ.get('REDIS_URL', 'redis://localhost:26379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

CELERY_BEAT_SCHEDULE = {
    'mark-offline-restaurants': {
        'task': 'tenants.tasks.mark_offline_restaurants',
        'schedule': 60.0,
    },
    'cleanup-old-data': {
        'task': 'tenants.tasks.cleanup_old_data',
        'schedule': crontab(hour=3, minute=30),
    },
}

# Cache (Redis) - used to store short-lived license/verification verdicts
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': os.environ.get('REDIS_URL', 'redis://localhost:26379/0'),
    }
}

# Postgres'dan farqli, Django test yugurishi uchun alohida Redis yaratmaydi -
# testlar dev keshi (restaurant_metrics_* kalitlari, throttle hisoblagichlari)
# bilan bitta bazani bo'lishib, bir-birini nondeterministik ifloslantiradi.
# Test rejimida alohida DB raqamiga o'tamiz.
if 'test' in sys.argv and CACHES['default']['LOCATION'].endswith('/0'):
    CACHES['default']['LOCATION'] = CACHES['default']['LOCATION'][:-2] + '/9'


def _load_pem(file_env, inline_env, default=''):
    """
    Reads a PEM key either from a file path (FILE_ENV) or from an inline
    env var (INLINE_ENV, with literal '\\n' sequences un-escaped). File
    path takes precedence when both are set. Missing files are tolerated
    (returns '') so the server can still boot before keys are provisioned -
    token issuance simply fails until LICENSE_PRIVATE_KEY is configured.
    """
    file_path = os.environ.get(file_env)
    if file_path:
        try:
            return Path(file_path).read_text()
        except FileNotFoundError:
            return default
    inline = os.environ.get(inline_env, default)
    return inline.replace('\\n', '\n') if inline else inline


# Licensing (JWT) settings - private key lives ONLY on the cloud (Ona) server.
LICENSE_PRIVATE_KEY = _load_pem('LICENSE_PRIVATE_KEY_FILE', 'LICENSE_PRIVATE_KEY')
LICENSE_TOKEN_TTL_DAYS = int(os.environ.get('LICENSE_TOKEN_TTL_DAYS', 7))
# Activate/renew issue this many sequential tokens in one call (each starting
# where the previous one expires) so a Bola that goes offline for weeks can
# keep rotating through pre-signed tokens locally, without ever holding the
# private key itself.
LICENSE_TOKEN_BATCH_SIZE = int(os.environ.get('LICENSE_TOKEN_BATCH_SIZE', 4))

# Spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'POS System Cloud API',
    'DESCRIPTION': 'Central Cloud API for all POS restaurants',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

def _read_latest_release_version():
    version_file = BASE_DIR.parent / 'local_server' / 'VERSION'
    if version_file.exists():
        return version_file.read_text().strip()
    return os.environ.get('LATEST_RELEASE_VERSION', '0.3.0')


LATEST_RELEASE_VERSION = _read_latest_release_version()

# Jazzmin Admin Settings
JAZZMIN_SETTINGS = {
    "site_title": "Mother Cloud Admin",
    "site_header": f"Cloud POS (v{LATEST_RELEASE_VERSION})",
    "site_brand": f"HQ POS v{LATEST_RELEASE_VERSION}",
    "welcome_sign": f"Mother POS Admin — Oxirgi versiya: v{LATEST_RELEASE_VERSION}",
    "copyright": f"POS System Cloud HQ (v{LATEST_RELEASE_VERSION})",

    "search_model": ["tenants.Restaurant", "tenants.License"],
    "show_ui_builder": False,
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user-shield",
        "auth.Group": "fas fa-users",
        "authtoken.Token": "fas fa-key",
        "authtoken.TokenProxy": "fas fa-key",
        "tenants.Restaurant": "fas fa-store",
        "tenants.RestaurantAdminAccount": "fas fa-user-tie",
        "tenants.License": "fas fa-id-card",
        "tenants.RemoteCommand": "fas fa-terminal",
        "tenants.ErrorLog": "fas fa-exclamation-triangle",
        "tenants.SyncedOrder": "fas fa-receipt",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",
}


JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",
    "dark_mode_theme": "darkly",
}

