# Generated by Django 5.2 on 2026-07-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('license_key', models.CharField(max_length=40)),
                ('jwt_token', models.TextField(blank=True, default='')),
                ('hardware_hash', models.CharField(max_length=128)),
                ('restaurant_id', models.UUIDField(blank=True, null=True)),
                ('restaurant_name', models.CharField(blank=True, default='', max_length=200)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('last_renewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_reason', models.CharField(blank=True, choices=[('remote_command', 'Onadan bloklandi'), ('license_inactive', 'Litsenziya nofaol')], default='', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Litsenziya holati',
                'verbose_name_plural': 'Litsenziya holati',
            },
        ),
    ]
