# Generated by Django 5.2 on 2026-07-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensestate',
            name='pending_tokens',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
