# Generated by Django 5.2 on 2026-07-10 08:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0002_licensestate_pending_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('level', models.CharField(choices=[('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], db_index=True, max_length=10)),
                ('logger_name', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField()),
                ('traceback', models.TextField(blank=True, default='')),
                ('module', models.CharField(blank=True, default='', max_length=200)),
                ('func_name', models.CharField(blank=True, default='', max_length=200)),
                ('line_no', models.PositiveIntegerField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('is_reported', models.BooleanField(db_index=True, default=False)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Xato jurnali',
                'verbose_name_plural': 'Xato jurnali',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['is_reported', 'occurred_at'], name='licensing_e_is_repo_081897_idx')],
            },
        ),
    ]
