# Generated by Django 5.2 on 2026-07-10 08:58

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0003_errorlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalErrorLog',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('event_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('level', models.CharField(choices=[('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], db_index=True, max_length=10)),
                ('logger_name', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField()),
                ('traceback', models.TextField(blank=True, default='')),
                ('module', models.CharField(blank=True, default='', max_length=200)),
                ('func_name', models.CharField(blank=True, default='', max_length=200)),
                ('line_no', models.PositiveIntegerField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('is_reported', models.BooleanField(db_index=True, default=False)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Xato jurnali',
                'verbose_name_plural': 'historical Xato jurnali',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLicenseState',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_index=True, default=1, editable=False)),
                ('license_key', models.CharField(max_length=40)),
                ('jwt_token', models.TextField(blank=True, default='')),
                ('pending_tokens', models.JSONField(blank=True, default=list)),
                ('hardware_hash', models.CharField(max_length=128)),
                ('restaurant_id', models.UUIDField(blank=True, null=True)),
                ('restaurant_name', models.CharField(blank=True, default='', max_length=200)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('last_renewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_reason', models.CharField(blank=True, choices=[('remote_command', 'Onadan bloklandi'), ('license_inactive', 'Litsenziya nofaol')], default='', max_length=50)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Litsenziya holati',
                'verbose_name_plural': 'historical Litsenziya holati',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
