# Generated by Django 5.2 on 2026-07-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0004_historicalerrorlog_historicallicensestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallicensestate',
            name='public_key',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='licensestate',
            name='public_key',
            field=models.TextField(blank=True, default=''),
        ),
    ]
