# Generated by Django 5.2 on 2026-07-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0005_historicallicensestate_public_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallicensestate',
            name='telegram_bot_token',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='historicallicensestate',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='licensestate',
            name='telegram_bot_token',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='licensestate',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
