"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import sys
from celery.schedules import crontab
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-oqs8bohdzf4x7z&139z7v!byl^n2zpnfy(%7m0fb%@61a3q+)h')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', '0') == '1'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')

# Cloudflare Tunnel orqali masofaviy admin kirish uchun (docs/4) - tunnel
# domenini shu yerga qo'shing (masalan: https://filial1.tizimingiz.uz).
CSRF_TRUSTED_ORIGINS = [
    origin for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if origin
]

if os.environ.get('SECURE_PROXY_SSL_HEADER', '0') == '1':
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    # daphne ENG BOSHIDA bo'lishi shart - shundagina `runserver` dev'da
    # avtomatik ASGI-aware bo'ladi (WebSocket'ni ham xizmat qiladi).
    'daphne',

    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party apps
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'drf_spectacular',
    'channels',
    'simple_history',

    # Local apps
    'core',
    'licensing',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',

    # Kill-switch: litsenziya yaroqsiz bo'lsa /api/ so'rovlarini bloklaydi.
    'licensing.middleware.LicenseEnforcementMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    # AuthenticationMiddleware'dan KEYIN bo'lishi shart - request.user'ni
    # thread-local'ga saqlab, HistoricalRecords yozuvlariga "kim o'zgartirdi"
    # (history_user) ma'lumotini avtomatik biriktiradi.
    'simple_history.middleware.HistoryRequestMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    MIDDLEWARE.append('core.middleware.SwaggerTokenPrefixMiddleware')

SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

# Real-vaqt (WebSocket) qatlami - mavjud Redis instansiyasi (cache/celery
# uchun ham ishlatiladigan) qayta ishlatiladi, yangi infratuzilma qo'shilmaydi.
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [{
                'address': os.environ.get('REDIS_URL', 'redis://localhost:6379/0'),
                'socket_timeout': 30,
                'socket_connect_timeout': 30,
                'retry_on_timeout': True,
            }],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'pos_local_db'),
        'USER': os.environ.get('DB_USER', 'pos_user'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'pos_password'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '15432'),
        'CONN_MAX_AGE': 600,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (Product/Category rasmlari). MEDIA_ROOT prod
# docker-compose.prod.yml'dagi mavjud `media_data:/app/media` volume bilan
# mos keladi - konteyner qayta yaratilganda rasm yo'qolmaydi. Dev'da alohida
# volume shart emas, chunki butun loyiha allaqachon `.:/app` bilan
# bind-mount qilingan (media/ .gitignore'da).
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'core.User'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.authentication.DeviceTokenAuthentication',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '10/minute',
        'user': '100/minute',
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'EXCEPTION_HANDLER': 'core.exceptions.custom_exception_handler',
}

# Test rejimida throttling o'chiriladi - suite bitta manzildan yuzlab so'rov
# yuboradi, throttle hisoblagichlari esa Redis'da test yugurishlari orasida
# ham saqlanib qolib, tasodifiy 429'lar bilan testlarni sindiradi.
# Rate'lar ham None: ba'zi view'lar throttle_classes'ni klass darajasida
# o'zi e'lon qiladi va DEFAULT_THROTTLE_CLASSES bo'shligi ularga ta'sir
# qilmaydi - rate None esa har qanday SimpleRateThrottle'ni o'chiradi.
if 'test' in sys.argv:
    REST_FRAMEWORK['DEFAULT_THROTTLE_CLASSES'] = []
    REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {'anon': None, 'user': None}

# Spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'POS System Local API',
    'DESCRIPTION': 'Local API for offline-first restaurant POS system',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# Celery settings
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Celery worker jarayoni sukut bo'yicha root logger'dagi handler'larni
# ishga tushganda olib tashlaydi (worker_hijack_root_logger default True) -
# shu qatorsiz Celery tasklaridagi ERROR/CRITICAL loglar runserver'da
# ishlab, celery_worker/celery_beat konteynerida jimgina yo'qolib qolar edi.
CELERY_WORKER_HIJACK_ROOT_LOGGER = False

CELERY_BEAT_SCHEDULE = {
    'send-heartbeat': {
        'task': 'licensing.tasks.send_heartbeat',
        'schedule': 60.0,
        'options': {'expires': 50},
    },
    'renew-license-daily': {
        'task': 'licensing.tasks.renew_license_token',
        'schedule': crontab(hour=3, minute=0),
    },
    'send-error-logs': {
        'task': 'licensing.tasks.send_error_logs',
        'schedule': 120.0,
        'options': {'expires': 100},
    },
    'cleanup-error-logs': {
        'task': 'licensing.tasks.cleanup_error_logs',
        'schedule': crontab(hour=4, minute=0),
    },
    'sync-completed-orders': {
        'task': 'licensing.tasks.sync_completed_orders',
        'schedule': 60.0,
        'options': {'expires': 50},
    },
    # Jismoniy printer navbatida qolib ketgan pending cheklarni qayta yuborish /
    # juda eskirganini failed qilish (core/tasks.py::sweep_stale_print_jobs).
    'sweep-stale-print-jobs': {
        'task': 'core.tasks.sweep_stale_print_jobs',
        'schedule': 120.0,
        'options': {'expires': 100},
    },
}

# Cache (Redis) - used to cache the license-verification verdict so the
# kill-switch middleware doesn't hit the DB on every request.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': os.environ.get('REDIS_URL', 'redis://localhost:6379/0'),
    }
}

# Postgres'dan farqli, Django test yugurishi uchun alohida Redis yaratmaydi -
# testlar dev keshi (PIN rate-limit kalitlari, litsenziya verdikti) bilan
# bitta bazani bo'lishib, bir-birini nondeterministik ifloslantiradi.
# Test rejimida alohida DB raqamiga o'tamiz.
if 'test' in sys.argv and CACHES['default']['LOCATION'].endswith('/0'):
    CACHES['default']['LOCATION'] = CACHES['default']['LOCATION'][:-2] + '/9'

# Error log reporting (Bola -> Ona)
ERROR_LOG_BATCH_SIZE = int(os.environ.get('ERROR_LOG_BATCH_SIZE', 200))
ERROR_LOG_RETENTION_DAYS = int(os.environ.get('ERROR_LOG_RETENTION_DAYS', 14))
ERROR_LOG_MAX_UNREPORTED = int(os.environ.get('ERROR_LOG_MAX_UNREPORTED', 5000))

# ERROR/CRITICAL darajadagi barcha loglarni (view'lardagi unhandled
# exception'lar, Celery tasklardagi xatoliklar, logger.error()/critical()
# chaqiruvlari) DatabaseErrorLogHandler orqali ErrorLog jadvaliga yozadi -
# keyinchalik send_error_logs task'i buni Onaga yuboradi. `django`/`celery`
# loggerlari odatda propagate=False bilan ishlaydi, shu sabab db_error_log
# ularga ALOHIDA berilgan - lekin aynan shuning uchun ular propagate=True
# qilinmasligi kerak, aks holda root'ga ham ko'tarilib ikki marta yozilib
# qolardi.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {'format': '{asctime} {levelname} {name} {message}', 'style': '{'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'verbose'},
        'db_error_log': {
            'class': 'licensing.log_handler.DatabaseErrorLogHandler',
            'level': 'ERROR',
        },
    },
    'root': {
        'handlers': ['console', 'db_error_log'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {'handlers': ['console', 'db_error_log'], 'level': 'INFO', 'propagate': False},
        'celery': {'handlers': ['console', 'db_error_log'], 'level': 'INFO', 'propagate': False},
    },
}


def _load_pem(file_env, inline_env, default=''):
    """
    Reads a PEM key either from a file path (FILE_ENV) or from an inline
    env var (INLINE_ENV, with literal '\\n' sequences un-escaped). File
    path takes precedence when both are set. Missing files are tolerated
    (returns '') so the server can still boot before keys are provisioned -
    the kill-switch/license code paths handle an empty key as "not configured".
    """
    file_path = os.environ.get(file_env)
    if file_path:
        try:
            return Path(file_path).read_text()
        except FileNotFoundError:
            return default
    inline = os.environ.get(inline_env, default)
    return inline.replace('\\n', '\n') if inline else inline


# App / licensing settings
# Versiya IMAGE ichiga joylashtiriladi (`local_server/VERSION` fayli, BASE_DIR
# ostida - Dockerfile `COPY . /app/` bilan olib kiradi, dev'da `.:/app` bind-
# mount orqali ko'rinadi). Fayl asosiy manba: shu tarzda Watchtower yangi image
# tortib konteynerni qayta yaratganda heartbeat'da hisobot qilinadigan
# `app_version` avtomatik yangilanadi - boshqa mashinaning `.env` fayliga
# tegmasdan. Aks holda `.env`da pin qilingan APP_VERSION yangi image tortilsa
# ham eski versiyani ko'rsatib turib, "update keldimi?" tekshiruvini buzardi.
# Env override faqat VERSION fayli topilmaganda zaxira sifatida ishlaydi.
def _read_app_version():
    try:
        text = (BASE_DIR / 'VERSION').read_text(encoding='utf-8').strip()
        if text:
            return text
    except OSError:
        pass
    return os.environ.get('APP_VERSION', '0.0.0')

APP_VERSION = _read_app_version()
ONA_SERVER_URL = os.environ.get('ONA_SERVER_URL', 'http://host.docker.internal:8001')

if not DEBUG and not ONA_SERVER_URL.startswith('https://'):
    raise ValueError("ONA_SERVER_URL must use https:// in production.")
LICENSE_PUBLIC_KEY = _load_pem('LICENSE_PUBLIC_KEY_FILE', 'LICENSE_PUBLIC_KEY')
LICENSE_ENFORCEMENT = os.environ.get('LICENSE_ENFORCEMENT', '0') == '1'
LICENSE_CLOCK_SKEW_SECONDS = int(os.environ.get('LICENSE_CLOCK_SKEW_SECONDS', 300))
LICENSE_EXP_GRACE_SECONDS = int(os.environ.get('LICENSE_EXP_GRACE_SECONDS', 0))
HARDWARE_ID_OVERRIDE = os.environ.get('HARDWARE_ID_OVERRIDE', '')
WATCHTOWER_URL = os.environ.get('WATCHTOWER_URL', 'http://watchtower:8080')
WATCHTOWER_TOKEN = os.environ.get('WATCHTOWER_TOKEN', '')

# Jazzmin Admin Settings
JAZZMIN_SETTINGS = {
    "site_title": "POS Admin",
    "site_header": "Local POS System",
    "site_brand": "Restaurant POS",
    "welcome_sign": "Welcome to the Local POS Admin",
    "copyright": "POS System Ltd",
    "search_model": ["core.User", "core.Order"],
    "show_ui_builder": False,
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "core.User": "fas fa-user-tie",
        "core.Table": "fas fa-chair",
        "core.TableZone": "fas fa-map-marked-alt",
        "core.Category": "fas fa-layer-group",
        "core.Product": "fas fa-hamburger",
        "core.Order": "fas fa-receipt",
        "core.OrderItem": "fas fa-utensils",
        "core.Payment": "fas fa-credit-card",
        "core.StaffDevice": "fas fa-mobile-alt",
        "core.DeviceRegistrationCode": "fas fa-ticket-alt",
        "core.Notification": "fas fa-bell",
        "core.RestaurantConfig": "fas fa-cogs",
        "core.Attendance": "fas fa-user-check",
        "core.Customer": "fas fa-user-friends",
        "core.DebtTransaction": "fas fa-hand-holding-usd",
        "core.Supplier": "fas fa-truck",
        "core.Ingredient": "fas fa-carrot",
        "core.ProductIngredient": "fas fa-mortar-pestle",
        "core.Purchase": "fas fa-dolly-flatbed",
        "core.StockMovement": "fas fa-exchange-alt",
        "authtoken.TokenProxy": "fas fa-key",
        "licensing.ErrorLog": "fas fa-exclamation-triangle",
        "licensing.LicenseToken": "fas fa-id-card",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",
}

JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",
    "dark_mode_theme": "darkly",
}

CORS_ALLOW_ALL_ORIGINS = True

