# Generated by Django 5.2 on 2026-07-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_restaurantconfig_attendance_historicalattendance_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='staffdevice',
            name='uniq_active_device_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='staffdevice',
            name='uniq_active_device_id',
        ),
        migrations.AddField(
            model_name='historicalstaffdevice',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffdevice',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='staffdevice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_approved', True)), fields=('user',), name='uniq_active_approved_device_per_user'),
        ),
        migrations.AddConstraint(
            model_name='staffdevice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_approved', True)), fields=('device_id',), name='uniq_active_approved_device_id'),
        ),
    ]
