# Generated by Django 5.2 on 2026-07-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_customer_ingredient_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprinter',
            name='chars_per_line',
            field=models.PositiveIntegerField(default=48, help_text="Bir qatordagi belgilar soni: 80mm qog'oz (XP-Q80A) - 48, 58mm - 32."),
        ),
        migrations.AddField(
            model_name='printer',
            name='chars_per_line',
            field=models.PositiveIntegerField(default=48, help_text="Bir qatordagi belgilar soni: 80mm qog'oz (XP-Q80A) - 48, 58mm - 32."),
        ),
        migrations.AlterField(
            model_name='historicalprinter',
            name='ip_address',
            field=models.CharField(blank=True, help_text="Bo'sh - virtual printer (chek faqat oshxona ekranida ko'rinadi). To'ldirilgan - ESC/POS baytlar shu manzilga TCP orqali avtomatik yuboriladi.", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='ip_address',
            field=models.CharField(blank=True, help_text="Bo'sh - virtual printer (chek faqat oshxona ekranida ko'rinadi). To'ldirilgan - ESC/POS baytlar shu manzilga TCP orqali avtomatik yuboriladi.", max_length=50, null=True),
        ),
    ]
