# Generated by Django 5.2 on 2026-07-23 07:43

import uuid
from django.db import migrations, models

def populate_qr_codes(apps, schema_editor):
    Table = apps.get_model('core', 'Table')
    for table in Table.objects.all():
        table.qr_code = uuid.uuid4()
        table.save(update_fields=['qr_code'])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_historicalprinter_chars_per_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltable',
            name='qr_code',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='table',
            name='qr_code',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(populate_qr_codes, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='table',
            name='qr_code',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
