# Generated by Django 5.2 on 2026-07-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_historicaltable_qr_code_table_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrestaurantconfig',
            name='public_domain',
            field=models.CharField(blank=True, default='', help_text="Mijozlar stoldagi QR kodni skanerlaganda o'tishi kerak bo'lgan restoran subdomeni (masalan: filial1.hamrohpos.uz)", max_length=255),
        ),
        migrations.AddField(
            model_name='restaurantconfig',
            name='public_domain',
            field=models.CharField(blank=True, default='', help_text="Mijozlar stoldagi QR kodni skanerlaganda o'tishi kerak bo'lgan restoran subdomeni (masalan: filial1.hamrohpos.uz)", max_length=255),
        ),
    ]
