# Generated by Django 5.2 on 2026-07-30 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_historicalrestaurantconfig_public_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprinter',
            name='mac_address',
            field=models.CharField(blank=True, help_text="Printerning Ethernet-ID'si. Kiritilib IP manzil bo'sh qoldirilsa, tizim PRINTER_IP_POOL diapazonidan bo'sh manzilni o'zi tanlaydi - keyin shu MAC uchun routerda DHCP reservation'ni qo'lda qo'yish qoladi.", max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="MAC (Ethernet-ID) AA:BB:CC:DD:EE:FF formatida bo'lishi kerak.", regex='^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$')]),
        ),
        migrations.AddField(
            model_name='printer',
            name='mac_address',
            field=models.CharField(blank=True, help_text="Printerning Ethernet-ID'si. Kiritilib IP manzil bo'sh qoldirilsa, tizim PRINTER_IP_POOL diapazonidan bo'sh manzilni o'zi tanlaydi - keyin shu MAC uchun routerda DHCP reservation'ni qo'lda qo'yish qoladi.", max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="MAC (Ethernet-ID) AA:BB:CC:DD:EE:FF formatida bo'lishi kerak.", regex='^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$')]),
        ),
    ]
