# Generated by Django 5.2 on 2026-07-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_historicalrestaurantconfig_public_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprinter',
            name='is_cashier',
            field=models.BooleanField(default=False, help_text="Kassa printeri (hisob-chek/shot va to'lov cheklari shu printerdan chiqadi)."),
        ),
        migrations.AddField(
            model_name='historicalprintjob',
            name='job_type',
            field=models.CharField(choices=[('kitchen', 'Oshxona bilet'), ('pre_bill', 'Hisob-chek (Shot)'), ('receipt', "To'lov cheki")], default='kitchen', max_length=20),
        ),
        migrations.AddField(
            model_name='printer',
            name='is_cashier',
            field=models.BooleanField(default=False, help_text="Kassa printeri (hisob-chek/shot va to'lov cheklari shu printerdan chiqadi)."),
        ),
        migrations.AddField(
            model_name='printjob',
            name='job_type',
            field=models.CharField(choices=[('kitchen', 'Oshxona bilet'), ('pre_bill', 'Hisob-chek (Shot)'), ('receipt', "To'lov cheki")], default='kitchen', max_length=20),
        ),
    ]
