# Generated by Django 5.2 on 2026-07-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_historicalprinter_is_cashier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrestaurantconfig',
            name='logo',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Restoran logotipi (chek uchun)'),
        ),
        migrations.AddField(
            model_name='historicalrestaurantconfig',
            name='name',
            field=models.CharField(default='Restoran', max_length=150, verbose_name='Restoran nomi'),
        ),
        migrations.AddField(
            model_name='restaurantconfig',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant/', verbose_name='Restoran logotipi (chek uchun)'),
        ),
        migrations.AddField(
            model_name='restaurantconfig',
            name='name',
            field=models.CharField(default='Restoran', max_length=150, verbose_name='Restoran nomi'),
        ),
    ]
