# Generated by Django 5.2 on 2026-07-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_historicalrestaurantconfig_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrestaurantconfig',
            name='service_charge_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Restoran xizmat haqi foizi (masalan 10.00 = 10%). Faqat admin/menejer o'zgartira oladi.", max_digits=5, verbose_name='Xizmat haqi foizi'),
        ),
        migrations.AddField(
            model_name='restaurantconfig',
            name='service_charge_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Restoran xizmat haqi foizi (masalan 10.00 = 10%). Faqat admin/menejer o'zgartira oladi.", max_digits=5, verbose_name='Xizmat haqi foizi'),
        ),
    ]
