# Generated by Django 5.2 on 2026-07-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_historicalrestaurantconfig_service_charge_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrestaurantconfig',
            name='telegram_bot_token',
            field=models.CharField(blank=True, default='', help_text="Bildirishnomalar uchun Telegram Bot Token (BotFather'dan olinadi)", max_length=200, verbose_name='Telegram Bot Token'),
        ),
        migrations.AddField(
            model_name='historicalrestaurantconfig',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', help_text='Bildirishnomalar yuboriladigan Telegram guruh yoki admin chat_id', max_length=100, verbose_name='Telegram Chat ID'),
        ),
        migrations.AddField(
            model_name='restaurantconfig',
            name='telegram_bot_token',
            field=models.CharField(blank=True, default='', help_text="Bildirishnomalar uchun Telegram Bot Token (BotFather'dan olinadi)", max_length=200, verbose_name='Telegram Bot Token'),
        ),
        migrations.AddField(
            model_name='restaurantconfig',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', help_text='Bildirishnomalar yuboriladigan Telegram guruh yoki admin chat_id', max_length=100, verbose_name='Telegram Chat ID'),
        ),
    ]
