# Generated by Django 5.2 on 2026-07-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_historicalregistersession_registersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='debttransaction',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Qaytarish muddati'),
        ),
        migrations.AddField(
            model_name='historicaldebttransaction',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Qaytarish muddati'),
        ),
    ]
