# Generated by Django 5.2 on 2026-08-01 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_debttransaction_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrestaurantconfig',
            name='phone',
            field=models.CharField(blank=True, default='', help_text="To'lov chekining pastida ko'rsatiladi (masalan +998901234567)", max_length=20, validators=[django.core.validators.RegexValidator(message="Telefon raqami +998xxxxxxxxx, 998xxxxxxxxx yoki xxxxxxxxx formatida bo'lishi kerak.", regex='^\\+?(998)?\\d{9}$')], verbose_name='Restoran telefon raqami'),
        ),
        migrations.AddField(
            model_name='restaurantconfig',
            name='phone',
            field=models.CharField(blank=True, default='', help_text="To'lov chekining pastida ko'rsatiladi (masalan +998901234567)", max_length=20, validators=[django.core.validators.RegexValidator(message="Telefon raqami +998xxxxxxxxx, 998xxxxxxxxx yoki xxxxxxxxx formatida bo'lishi kerak.", regex='^\\+?(998)?\\d{9}$')], verbose_name='Restoran telefon raqami'),
        ),
    ]
